version: 0
os: linux
files:
  - source: /
    destination: /home/ubuntu
    permissions:
      - object: script
        pattern: before-deploy-script.sh
        mode: "0755"
      - object: script
        pattern: deploy-script.sh
        mode: "0755"
hooks:
  AfterInstall:
    - location: before-deploy-script.sh
      runas: ubuntu
      timeout: 1800
  ApplicationStart:
    - location: deploy-script.sh
      runas: ubuntu
      timeout: 1800
