version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
hooks:
  BeforeInstall:
    - location: /home/ubuntu/before-deploy-script.sh
      runas: ubuntu
      timeout: 1800
  AfterInstall:
    - location: /home/ubuntu/deploy-script.sh
      runas: ubuntu
      timeout: 1800
