---
version: 0
os: linux
files:
  - source: /
    destination: /home/ubuntu
hooks:
  BeforeInstall:
    - location: before-deploy-script.sh
      runas: ubuntu
      timeout: 1800
  AfterInstall:
    - location: deploy-script.sh
      runas: ubuntu
      timeout: 1800
