version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/devops-assessment
hooks:
  AfterInstall:
    - location: /home/ubuntu/devops-assessment/deploy-script.sh
      runas: ubuntu
      timeout: 1800
