name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd devops-assessment-main
          npm install
          npm install next

      - name: Build Next.js application
        run: |
          cd devops-assessment-main
          npm run build

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

            # Stop the Next.js application managed by PM2
            pm2 stop nextjs

            # Remove all old files in the deployment directory
            rm -rf /home/ubuntu/devops-assessment/*

            # Copy the build files to the EC2 instance
            scp -r devops-assessment-main/.next/* ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/ubuntu/devops-assessment/

            # Start the Next.js application managed by PM2
            pm2 start nextjs

            # Restart or reload Nginx
            sudo systemctl restart nginx
