name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: cd /home/runner/work/sr_devops_challenges/sr_devops_challenges/devops-assessment-main && npm install && npm install next

    - name: Build Next.js application
      run: cd /home/runner/work/sr_devops_challenges/sr_devops_challenges/devops-assessment-main && npm run build

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/runner/work/sr_devops_challenges/sr_devops_challenges/devops-assessment-main
          ls -alt
          pm2 stop nextjs
          cp -R * /home/ubuntu/devops-assessment
          pm2 start nextjs
          sudo systemctl restart nginx
