name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
      - uat

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build Next.js application
        run: npm run build

      - name: Deploy to EC2
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MAIN_EC2_HOST }}
          username: ${{ secrets.MAIN_EC2_USERNAME }}
          key: ${{ secrets.MAIN_SSH_PRIVATE_KEY }}
          script: |
            # Deployment script for main branch

      - name: Deploy to Dev Environment
        if: github.ref == 'refs/heads/dev'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_EC2_HOST }}
          username: ${{ secrets.DEV_EC2_USERNAME }}
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          script: |
            # Deployment script for dev branch

      - name: Deploy to UAT Environment
        if: github.ref == 'refs/heads/uat'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.UAT_EC2_HOST }}
          username: ${{ secrets.UAT_EC2_USERNAME }}
          key: ${{ secrets.UAT_SSH_PRIVATE_KEY }}
          script: |
            # Deployment script for uat branch
